// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQga3Ln6zPcg5s19ZZzIlGfKFT9BQ6El4',
    appId: '1:375880045336:web:505436b00172b13cc6c46d',
    messagingSenderId: '375880045336',
    projectId: 'kirana-store-ee7fd',
    authDomain: 'kirana-store-ee7fd.firebaseapp.com',
    storageBucket: 'kirana-store-ee7fd.firebasestorage.app',
    measurementId: 'G-LZZ7DNMD69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-XWbKmVJ5uighHuH-5uWqLX0odINsBM',
    appId: '1:375880045336:android:2d03963907818b76c6c46d',
    messagingSenderId: '375880045336',
    projectId: 'kirana-store-ee7fd',
    storageBucket: 'kirana-store-ee7fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQ9mTE5NGPjwHDanljZF5emlgXpQmb68',
    appId: '1:375880045336:ios:982b847a44a2b3e2c6c46d',
    messagingSenderId: '375880045336',
    projectId: 'kirana-store-ee7fd',
    storageBucket: 'kirana-store-ee7fd.firebasestorage.app',
    iosBundleId: 'com.example.appDevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQ9mTE5NGPjwHDanljZF5emlgXpQmb68',
    appId: '1:375880045336:ios:982b847a44a2b3e2c6c46d',
    messagingSenderId: '375880045336',
    projectId: 'kirana-store-ee7fd',
    storageBucket: 'kirana-store-ee7fd.firebasestorage.app',
    iosBundleId: 'com.example.appDevProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQga3Ln6zPcg5s19ZZzIlGfKFT9BQ6El4',
    appId: '1:375880045336:web:25487ec15384a65bc6c46d',
    messagingSenderId: '375880045336',
    projectId: 'kirana-store-ee7fd',
    authDomain: 'kirana-store-ee7fd.firebaseapp.com',
    storageBucket: 'kirana-store-ee7fd.firebasestorage.app',
    measurementId: 'G-DMJ7MZNP0L',
  );

}